name: CI-CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.actor}}-${{ github.run_number }}
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.git/
            !${{ github.workspace }}/.github/
      - name: Download Zip Artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.actor}}-${{ github.run_number }}
          path: ./temp
      - name: Zip Downloaded Files (Again)
        run: zip -r ${{ github.actor}}-${{ github.run_number }}.zip ./
      - name: Create Release
        if: success()
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - Adjusted alliance costs to scale with allies' maximum military strength
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ github.actor}}-${{ github.run_number }}.zip
          asset_name: ${{ github.actor}}-${{ github.run_number }}.zip
          asset_content_type: application/zip
